/**
 * Generated by `npm run registry` — do not edit.
 *
 * The plugin files and stylesheets in load order, for the contexts that cannot
 * read the folder: the Chromium service worker's `importScripts` and the
 * Firefox background scripts. Node tools read `src/plugins/` directly.
 * `npm run registry:check` fails if this is stale.
 */
globalThis.GITALIKE_PLUGIN_FILES = {
  "js": [
    "plugins/core.js",
    "plugins/skins/bitbucket/index.js",
    "plugins/skins/github/index.js",
    "plugins/skins/gitlab/index.js",
    "plugins/sources/bitbucket/index.js",
    "plugins/sources/gerrit/index.js",
    "plugins/sources/gitea/index.js",
    "plugins/sources/github/index.js",
    "plugins/sources/gitlab/index.js"
  ],
  "css": [
    "themes/gs-tokens.css",
    "plugins/skins/bitbucket/as-bitbucket.css",
    "plugins/skins/github/as-github.css",
    "plugins/skins/gitlab/as-gitlab.css",
    "themes/ux-markers.css",
    "themes/ux-nav.css"
  ]
};
